version: '3.6'

services:
  db:
    image: mysql
    container_name: mysql
    restart: always
    ports:
     - 3306:3306
    env_file: .env
    command:
      - --character-set-client-handshake=FALSE
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./db/initdb.d:/docker-entrypoint-initdb.d
      - /var/lib/mysql:/var/lib/mysql

  frontend:
    container_name: blockai_front
    build:
      dockerfile: Dockerfile
      context: ./frontend
    ports:
     - 3000:80
    networks:
      - blockai
    restart: unless-stopped
    depends_on:
      - backend

  backend:
    container_name: blockai_back
    build:
      dockerfile: Dockerfile
      context: ./backend
    ports:
     - 8080:8080
    env_file: .env
    networks:
      - blockai
    restart: unless-stopped
    depends_on:
      - db

networks:
  blockai: