spring:
  datasource:
    url: jdbc:h2:~/test;
    driver-class-name: org.h2.Driver
    username: blockai
    password: 1234

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: false
