spring:
  datasource:
    url: jdbc:h2:~/test;
    driver-class-name: org.h2.Driver
    username: blockai
    password: 1234
    tomcat:
      test-on-borrow: true
      validation-query: SELECT 1

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: false
