server:
  port: 8080

spring:
  profiles:
    active: local
    include: aws, ethereum

---

cloud:
  aws:
    stack:
      auto: false
    region:
      static: ${AWS_REGION}
    credentials:
      instance-profile: true
    s3:
      bucket: blockai-bucket