server:
  port: 8080

spring:
  profiles:
    active: local

---

cloud:
  aws:
    stack:
      auto: false
    region:
      static: ap-northeast-2
    credentials:
      instance-profile: true
      access-key: AKIARRTWNAL74NM4XSMZ
      secret-key: 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

    s3:
      bucket: blockai-bucket


