server:
  port: 8080

spring:
  profiles:
    active: local

---

cloud:
  aws:
    stack:
      auto: false
    region:
      static: ${AWS_REGION}
    credentials:
      instance-profile: true
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}

    s3:
      bucket: blockai-bucket


