server:
  port: 8080

spring:
  profiles:
    active: local

---

cloud:
  aws:
    stack:
      auto: false
    region:
      static: ap-northeast-2
    credentials:
      instance-profile: true
      access-key: AKIARRTWNAL74NM4XSMZ
      secret-key: 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

    s3:
      bucket: blockai-bucket

ethereum:
  from: "0x3861ce91ED1b8dE311F025923F711EA07a8501c1"
  contract: "0x94aA46Fc81D4f59f01048319417d074803f067d4"
  networkUrl: "https://ropsten.infura.io/v3/9aa3d95b3bc440fa88ea12eaa4456161"
  privateKey: "0xaca10c42b1fe8262a88f696e5c389a895f1091e8bec36a3f41a8fbd47d3f1f1b"